import type { Metadata } from "next";
import { Inter } from "next/font/google";
{{#if fetching}}
import { QueryProvider } from "@/lib/QueryProvider";
{{/if}}
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "{{appName}}",
  description: "Generated by @oss-ma/tpl",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {{#if fetching}}
        <QueryProvider>{children}</QueryProvider>
        {{/if}}
        {{#unless fetching}}
        {children}
        {{/unless}}
      </body>
    </html>
  );
}